global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'opnsense'
    static_configs:
      - targets: ['192.168.179.1:9100']

  - job_name: node_exporter
    static_configs:
      - targets:
          - "192.168.179.20:9100"

  - job_name: smartctl_exporter
    static_configs:
      - targets:
          - "192.168.179.20:9633"

  - job_name: pve
    static_configs:
      - targets:
        - 192.168.178.225
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.179.24:9221 # PVE address
