---
services:
  pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    container_name: pve-exporter
    ports:
      - "9221:9221"
    restart: unless-stopped
    volumes:
      - ./pve.yml:/etc/prometheus/pve.yml
    labels:
      org.label-schema.group: "monitoring"
